In [1]:
import re
from itertools import zip_longest
import gc

import xml.etree.ElementTree as ET
import numpy as np
from datetime import datetime

"""
ToyNetwork 재분석
    화성~서울 네트워크(서울방향만)
    집계시간 : 10~30초
    분석시간 1800~13200 중 1800~12600 사용
    램프 ALL
    본선부 구간2 - 150m 상류 검지기
    모형식 EL 방법론 수정
"""
import pandas as pd

import os

"""
pd.set_option("display.max_rows", None)      # 모든 행 표시
pd.set_option("display.max_columns", None)   # 모든 열 표시
pd.set_option("display.width", None)         # 출력 폭 제한 해제
pd.set_option("display.max_colwidth", None)  # 셀 내용 생략 방지
"""

# FIX 값 모음
###################################################################################################################

path = r"C:\Vissim_Workspace\시나리오(140-유고지점 Uniform Random)_260518\본선부\구간2"

senario_path = r"C:\Users\alswl\Desktop\유고 시나리오\추정용 시나리오\synthetic_scenarios_all_140_with_set_type(본선부-구간2).csv"

inpx_path = r"C:\Vissim_Workspace\시나리오(140-유고지점 Uniform Random)_260518\본선부\구간2\화성~서울(140-유고지점)_260526.inpx"

# 한번에 처리할 .mer파일 갯수
num_mer = 3

# 임계 연속 시간
continuous_list = [180]


# 집계시간(분)
#min_time = 10 #5,10,15

# 집계시간(초)
sec_time_list = [10, 20, 30]

# 상류 검지기 위치(150m, 250m, 350m)
up_dcp_pos_list = [1, 2, 3]

#대/시 환산
revision_time = None

start_interval = 1800
end_use_interval = 12600
end_interval = 13200

weights = {
    "w1" : 1,
    "w2" : 1,
    "w3" : 1,
    "w4" : 1,
    "w5" : 1,
    "w6" : 1
}

vehicle_types = [100, 300, 630, 640, 650]
###################################################################################################################
"""
    모델 모형식 변수
"""

# 유고 발생 전 차로 수
lane = None

# 유고 발생 차로 수
acc_lane = None

# 유고 발생 시간(초)
acc_start_time = 3600

# 유고 해제 시간(초)
#acc_finish_list = [3300, 3900, 4800, 5700, 6600] # 5분, 15분, 30분, 45분, 60분
acc_finish_time = None
# 종단 경사
lane_gradient = None

# 유고 지점
incident_measurement = None

# 임계시간
Vc = 53.7

# 램프 간섭 영향률
###################################################################################################################
# 램프 전 본선 검지기(램프 간섭 영향률)
before_ramp = [70, 117, 124, 186, 215]

# 램프 후 본선 검지기(램프 간섭 영향률)
after_ramp = [74, 121, 127, 190, 221]

# 유입램프 검지기(램프 간섭 영향률)
input_ramp = [902, 904]

# 유출램프 검지기(램프 간섭 영향률)
output_ramp = [901, 903, 905]

# 진출 정상성(진입)(진출 원활률)
enter_line = [23, 121, 190]

# 유입램프 바로 뒤 본선 검지기(진출 원활률)(램프 간섭 영향률)
input_main_ramp = [121, 190]

# 유출램프 바로 앞 본선 검지기(진출 원활률)(램프 간섭 영향률)
output_main_ramp = [73, 126, 220]

# 3차로 검지기
three_lane = [71, 72, 73, 119, 120, 125, 126, 188, 189, 216, 217, 218, 219, 220]
###################################################################################################################


# 함수 모음
###################################################################################################################

# 시간순으로 데이터 정렬
def sort_ascending(df):
    # 먼저 시간 순서용 StartTime 생성
    df["StartTime"] = (
        df["TimeGroup"]
        .astype(str)
        .str.split("~")
        .str[0]
        .astype(int)
    )
    df["EndTime"] = (
        df["TimeGroup"]
        .astype(str)
        .str.split("~")
        .str[1]
        .astype(int)
    )
    # 반드시 V_next 계산 전에 정렬
    df = df.sort_values(["StartTime", "EndTime", "New_Measurement"]).reset_index(drop=True)

    return df

# 속도 변화율
def speed_mean(original_df):
    copy_df = original_df.copy()

    # 램프 검지기 제외
    copy_df = copy_df[~copy_df["New_Measurement"].between(900, 910)]

    measurements = sorted(copy_df["New_Measurement"].dropna().unique())

    # TimeGroup, New_Measurement별 그룹화 및 속도 평균
    speed_mean_df = (
        copy_df.groupby(["TimeGroup", "New_Measurement"])
          .agg(V_mean=("v[km/h]", "mean"), V_count=("v[km/h]", "count"))
          .reset_index()
    )

    speed_mean_df = complete_time_measurement(
        speed_mean_df,
        value_cols=["V_mean", "V_count"],
        measurements=measurements
    )

    speed_mean_df["V_next"] = speed_mean_df.groupby("TimeGroup")["V_mean"].shift(-1)
    cols=["V_mean", "V_next"]
    speed_mean_df[cols] = speed_mean_df[cols].fillna(0)
    speed_mean_df["delta_V"] = np.where(speed_mean_df["V_mean"] == 0,
        0,
        (speed_mean_df["V_next"] - speed_mean_df["V_mean"]) / speed_mean_df["V_mean"]
    )

    return speed_mean_df

# 밀도 변화율
def density_mean(speed_df):
    density_mean_df  = speed_df.copy()

    density_mean_df["K"] = np.where(
        density_mean_df["V_mean"] == 0,
        0,
        density_mean_df["V_count"] * revision_time / density_mean_df["V_mean"]
    )
    density_mean_df["K_next"] = density_mean_df.groupby("TimeGroup")["K"].shift(-1)
    cols=["K", "K_next"]
    density_mean_df[cols] = density_mean_df[cols].fillna(0)
    density_mean_df["delta_K"] = np.where(density_mean_df["K"] == 0,
        0,
        (density_mean_df["K_next"] - density_mean_df["K"]) / density_mean_df["K"]
    )

    density_mean_df = complete_time_measurement(
        density_mean_df,
        value_cols=["V_mean", "V_count", "K", "K_next", "delta_K"]
    )
    return density_mean_df

# 중차량 혼입률
def heavy_rate(original_df):
    copy_df = original_df.copy()

    measurements = sorted(copy_df["New_Measurement"].dropna().unique())

    heavy_df = (
        copy_df.groupby(["TimeGroup", "New_Measurement"])
        .agg(
            heavy_count=("Vehicle type", lambda x: x.isin([630, 640, 650]).sum()),
            total_count=("Vehicle type", "count")
        )
        .reset_index()
    )
    heavy_df = sort_ascending(heavy_df)

    heavy_df = complete_time_measurement(
        heavy_df,
        value_cols=["heavy_count", "total_count"],
        measurements=measurements
    )

    heavy_df["rate"] = np.where(
        heavy_df["total_count"] == 0,
        0,
        heavy_df["heavy_count"] / heavy_df["total_count"]
    )

    return heavy_df

# 동적 포화도
def entry_saturation(original_df):
    copy_df = original_df.copy()

    copy_df = copy_df[~copy_df["New_Measurement"].between(900, 910)]

    measurements = sorted(copy_df["New_Measurement"].dropna().unique())

    # 실측용량 C(2차로 4400)
    entry_saturation_df = (
        copy_df.groupby(["TimeGroup", "New_Measurement"])
        .size()
        .reset_index(name="entry_volume")  # 차량 수를 entry_volume이라는 컬럼명으로
    )

    entry_saturation_df = complete_time_measurement(
        entry_saturation_df,
        value_cols=["entry_volume"],
        measurements=measurements
    )

    entry_saturation_df = sort_ascending(entry_saturation_df)

    # 행별 capacity 설정
    entry_saturation_df["capacity"] = np.where(
        entry_saturation_df["New_Measurement"].isin(three_lane),
        6600,   # 3차로
        4400    # 2차로
    )

    entry_saturation_df["Phi_진입"] = entry_saturation_df["entry_volume"] * revision_time / entry_saturation_df["capacity"]

    return entry_saturation_df

# 램프 간섭 영향률
def rfr_rate(original_df):
    copy_df = original_df.copy()
    copy_df = copy_df[copy_df["TimeGroup"].notna()]
    copy_df["TimeGroup"] = copy_df["TimeGroup"].astype(str)
    main_results=[]

    for i, (before, after) in enumerate(zip(before_ramp, after_ramp)):
        q_before = (copy_df[copy_df["New_Measurement"] == before] # 70, 117, 124, 186, 215, 312, 342, 403, 412, 460
                    .groupby("TimeGroup")
                    .size()
                    .reset_index(name="q_before"))

        q_after = (copy_df[copy_df["New_Measurement"] == after] # 74, 121, 127, 190, 221, 317, 345, 406, 416, 465
                   .groupby("TimeGroup")
                   .size()
                   .reset_index(name="q_after"))

        merged = q_before.merge(q_after, on="TimeGroup", how="outer").fillna(0)
        merged["before_ramp"] =  before
        merged["after_ramp"] =  after
        merged["Qm"] = (merged["q_before"] + merged["q_after"]) / 2
        main_results.append(merged)


    ramp_results = []
    for input_, output_ in zip_longest(input_ramp, output_ramp):

        if output_ is not None:
            q_out = (copy_df[copy_df["New_Measurement"] == output_] # 901, 903, 905
                     .groupby("TimeGroup").size().reset_index(name="q_out"))
            q_out["New_Measurement"] = output_
            ramp_results.append(q_out)

        if input_ is not None:
            q_in = (copy_df[copy_df["New_Measurement"] == input_] # 902, 904
                    .groupby("TimeGroup").size().reset_index(name="q_in"))
            q_in["New_Measurement"] = input_
            ramp_results.append(q_in)


    input_queue = input_main_ramp.copy() # 100
    output_queue = output_main_ramp.copy() #
    rfr_list = []

    for i in range(min(len(main_results), len(ramp_results))):
        main_df = main_results[i]
        ramp_df = ramp_results[i]

        rfr_df = pd.merge(main_df, ramp_df, on="TimeGroup", how="outer").fillna(0)

        # 기본값 초기화
        rfr_df["IR_in"] = 0
        rfr_df["IR_out"] = 0

        # q_in 있을 때 (유입)
        if "q_in" in rfr_df.columns:
            rfr_df["IR_in"] = np.where(
                rfr_df["Qm"] == 0,
                0,
                rfr_df["q_in"] / rfr_df["Qm"]
            )
            if input_queue:  # 남은 게 있으면 하나 꺼냄
                current_input = input_queue.pop(0)
                rfr_df["New_Measurement"] = current_input

        # q_out 있을 때 (유출)
        if "q_out" in rfr_df.columns:
            rfr_df["IR_out"] = np.where(
                rfr_df["Qm"] == 0,
                0,
                rfr_df["q_out"] / rfr_df["Qm"]
            )
            if output_queue:
                current_output = output_queue.pop(0)
                rfr_df["New_Measurement"] = current_output

        rfr_df["RFR"] = rfr_df["IR_in"] + rfr_df["IR_out"]

        rfr_list.append(rfr_df)

    if not rfr_list:
        base = copy_df[["TimeGroup"]].drop_duplicates().copy()
        all_measurements = copy_df["New_Measurement"].unique()

        expanded = []
        for m in all_measurements:
            temp = base.copy()
            temp["New_Measurement"] = m
            temp["RFR"] = 0
            expanded.append(temp)

        final_rfr_df = pd.concat(expanded, ignore_index=True)
        final_rfr_df = final_rfr_df.sort_values(by=["TimeGroup", "New_Measurement"]).reset_index(drop=True)
        final_rfr_df["RFR"] = final_rfr_df["RFR"].fillna(0)
    else :
        # -----------------------------
        # 특정 검지기에만 RFR 반영
        # -----------------------------
        final_rfr_df = pd.concat(rfr_list, ignore_index=True)

        target_measurements = input_main_ramp + output_main_ramp
        all_measurements = copy_df["New_Measurement"].unique()

        expanded_df_list = []

        base_rfr_df = final_rfr_df.copy()

        for m in all_measurements:
            if m in target_measurements:
                temp = base_rfr_df[base_rfr_df["New_Measurement"] == m].copy()
            else:
                temp = base_rfr_df[["TimeGroup"]].drop_duplicates().copy()
                temp["New_Measurement"] = m
                temp["RFR"] = 0

            expanded_df_list.append(temp)

        final_rfr_df = pd.concat(expanded_df_list, ignore_index=True)
        final_rfr_df = final_rfr_df.sort_values(by=["TimeGroup", "New_Measurement"]).reset_index(drop=True)
        final_rfr_df = final_rfr_df[["TimeGroup", "New_Measurement", "RFR"]]
        final_rfr_df["RFR"] = final_rfr_df["RFR"].fillna(0)

    final_rfr_df = sort_ascending(final_rfr_df)

    final_rfr_df = complete_time_measurement(
        final_rfr_df,
        value_cols=["RFR"]
    )
    return final_rfr_df


# 진출 원활율- output_main_ramp
def output_normality(original_df):
    copy_df = original_df.copy()

    copy_df = copy_df[copy_df["TimeGroup"].notna()]

    normality_list = []

    # 여러 진입/진출 쌍 처리
    for enter, exit_ramp, exit_main in zip(enter_line, output_ramp, output_main_ramp):
        entry_df = copy_df[copy_df["New_Measurement"] == enter][["New_Measurement", "VehNo", "t(Entry)"]]

        exit_df  = copy_df[copy_df["New_Measurement"] == exit_ramp][["New_Measurement", "VehNo", "t(Entry)"]]

        # 차량 번호별 최소 통과시각
        entry_first = (
            entry_df.groupby("VehNo")["t(Entry)"].min()
            .reset_index()
            .rename(columns={"t(Entry)": "t_entry"})
        )

        exit_first = (
            exit_df.groupby("VehNo")["t(Entry)"].min()
            .reset_index()
            .rename(columns={"t(Entry)": "t_exit"})
        )

        # 진입-진출 매칭 후 지연시간 계산
        merged = pd.merge(entry_first, exit_first, on="VehNo", how="inner")
        merged["delay_sec"] = merged["t_exit"] - merged["t_entry"]
        merged = merged[merged["delay_sec"] >= 0]  # 음수 제거

        # 중간값 기반 시간지연 bin 계산
        if len(merged) and np.isfinite(np.nanmedian(merged["delay_sec"])):
            lag_bins = int(round(np.nanmedian(merged["delay_sec"]) / sec_time))
        else:
            lag_bins = 0

        # 진입/진출 카운트 집계
        entry_count = (
            copy_df[copy_df["New_Measurement"] == enter]
            .groupby("TimeGroup")
            .size()
            .reset_index(name="Q_in")
        )

        exit_count = (
            copy_df[copy_df["New_Measurement"] == exit_ramp]
            .groupby("TimeGroup")
            .size()
            .reset_index(name="Q_out")
        )

        # 병합 후 지연만큼 shift
        merged_counts = pd.merge(entry_count, exit_count, on="TimeGroup", how="left")


        merged_counts["Q_out_shift"] = merged_counts["Q_out"].shift(-lag_bins)



        merged_counts["F(outrate)"] = np.where(
            merged_counts["Q_in"] == 0,
            0,
            merged_counts["Q_out_shift"] / merged_counts["Q_in"]
        )

        merged_counts["New_Measurement"] = exit_main  # 진출 지점에 부여

        normality_list.append(merged_counts)

    if not normality_list:
        base = copy_df[["TimeGroup"]].drop_duplicates().copy()
        all_measurements = copy_df["New_Measurement"].unique()
        expanded = []
        for m in all_measurements:
            temp = base.copy()
            temp["New_Measurement"] = m
            temp["F(outrate)"] = 0
            expanded.append(temp)

        final_df = pd.concat(expanded, ignore_index=True)
        final_df = final_df.sort_values(by=["TimeGroup", "New_Measurement"]).reset_index(drop=True)
        final_df["F(outrate)"] = final_df["F(outrate)"].fillna(0)

    else :
        # 모든 진출 램프 결과 병합
        final_df = pd.concat(normality_list, ignore_index=True)

        # 전체 검지기 확장
        all_measurements = copy_df["New_Measurement"].unique()
        expanded_list = []

        for m in all_measurements:
            if m in output_main_ramp:
                temp = final_df[final_df["New_Measurement"] == m].copy()
            else:
                temp = final_df[["TimeGroup"]].drop_duplicates().copy()
                temp["New_Measurement"] = m
                temp["F(outrate)"] = 0
            expanded_list.append(temp)

        final_df = pd.concat(expanded_list, ignore_index=True)
        final_df = final_df.sort_values(by=["TimeGroup", "New_Measurement"]).reset_index(drop=True)
    final_df = sort_ascending(final_df)

    final_df = complete_time_measurement(
        final_df,
        value_cols=["F(outrate)"]
    )
    return final_df


def calculate_stvm(speed_df, density_df, heavy_df, entry_saturation_df, rfr_df, normality_df):

    merged_df = (
        speed_df[["TimeGroup", "New_Measurement", "delta_V"]]
        .merge(
            density_df[["TimeGroup", "New_Measurement", "delta_K"]],
            on=["TimeGroup", "New_Measurement"],
            how="outer"
        )
        .merge(
            heavy_df[["TimeGroup", "New_Measurement", "rate"]],
            on=["TimeGroup", "New_Measurement"],
            how="outer"
        )
        .merge(
            entry_saturation_df[["TimeGroup", "New_Measurement", "Phi_진입"]],
            on=["TimeGroup", "New_Measurement"],
            how="outer"
        )
        .merge(
            rfr_df[["TimeGroup", "New_Measurement", "RFR"]],
            on=["TimeGroup", "New_Measurement"],
            how="outer"
        )
        .merge(
            normality_df[["TimeGroup", "New_Measurement", "F(outrate)"]],
            on=["TimeGroup", "New_Measurement"],
            how="outer"
        )
    )

    merged_df.fillna(0, inplace=True)

    merged_df["STVM"] = (
        weights["w1"] * merged_df["delta_V"] +
        weights["w2"] * merged_df["delta_K"] +
        weights["w3"] * merged_df["rate"] +
        weights["w4"] * merged_df["Phi_진입"] +
        weights["w5"] * merged_df["RFR"] +
        weights["w6"] * merged_df["F(outrate)"]
    )
    merged_df.replace([np.inf, -np.inf], 0, inplace=True)
    merged_df = modify_frame(merged_df)
    return merged_df

def calc_z(df):
    copy_df = df.copy()
    if copy_df.empty:
        return copy_df

    # 검지기별 평균
    stvm_avg_df = (
        copy_df
        .groupby("New_Measurement")["STVM"]
        .mean()
        .reset_index(name="STVM_MEAN")
    )



    avg_stvm = stvm_avg_df["STVM_MEAN"].mean()
    std_stvm = stvm_avg_df["STVM_MEAN"].std(ddof=0)

    stvm_avg_df["Z-변환"] = (stvm_avg_df["STVM_MEAN"] - avg_stvm) / std_stvm

    z_max = stvm_avg_df["Z-변환"].max()
    z_min = stvm_avg_df["Z-변환"].min()
    stvm_avg_df["환산점수"] = stvm_avg_df["Z-변환"].apply(lambda z: z_to_score(z, z_min, z_max))

    return stvm_avg_df

def calculate_z_score(stvm_df):
    copy_df = stvm_df.copy()

    # 구간 나누기
    group1 = copy_df[copy_df["New_Measurement"].between(1, 265)].copy()

    group1 = calc_z(group1)

    merged = group1.sort_values(by="New_Measurement")
    #save_to_excel(merged, folder_path, "환산점수 원시데이터", i)

    #stvm_df = pd.pivot(merged, index="TimeGroup", columns= "New_Measurement", values="환산점수")

    return merged

def modify_frame(df):
    modify_df = df.copy()
    modify_df["StartTime"] = modify_df["TimeGroup"].str.split("~").str[0].astype(int)
    modify_df["EndTime"] = modify_df["TimeGroup"].str.split("~").str[1].astype(int)
    modify_df = modify_df[(modify_df["StartTime"] >=start_interval) &(modify_df["EndTime"] <= end_use_interval)]
    modify_df = modify_df[~modify_df["New_Measurement"].isin([266, 901, 902, 903, 904, 905])]

    modify_df.sort_values(["StartTime", "New_Measurement"], inplace=True)

    return modify_df


def variable_timegroup_avg(stvm_df):
    copy_df = stvm_df.copy()
    variable_time_df = copy_df.groupby("TimeGroup")[["delta_V", "delta_K", "rate", "Phi_진입", "RFR", "F(outrate)"]].mean()
    return variable_time_df

def variable_total_avg(variable_df):
    variable_total_df = pd.DataFrame([variable_df.mean(numeric_only=True)])
    return variable_total_df

def speed_density_avg(density_df):
    copy_df = density_df.copy()
    avg_df = modify_frame(copy_df)
    avg_df = pd.DataFrame([avg_df.mean(numeric_only=True)])
    avg_df = avg_df[["V_mean", "K"]]
    return avg_df

def pivot_table(df, value, preprocess=None):
    copy_df = df.copy()
    if preprocess :
        copy_df = preprocess(copy_df)
    copy_df = copy_df.pivot(index="TimeGroup", columns="New_Measurement", values=value)

    copy_df = (
        copy_df
        .assign(_t=lambda x: x.index.astype(str).str.split("~").str[0].astype(int))
        .sort_values("_t")
        .drop(columns="_t")
    )
    copy_df = copy_df.fillna(0)
    return copy_df

def excel_color(val):
    if pd.isna(val):
        return ""
    elif val <= 0:
        return "background-color: #FF0000" # 빨간색
    else:
        return "background-color: #FFC000"  # 주황색


def weighted_avg_speed(original_df):
    copy_df = original_df.copy()
    # TimeGroup, New_Measurement별 그룹화 및 속도 평균
    speed_mean_df = (
        copy_df.groupby(["TimeGroup", "New_Measurement", "Vehicle type"])
          .agg(V_mean=("v[km/h]", "mean"), V_count=("v[km/h]", "count"))
          .reset_index()
    )
    speed_mean_df["std_group"] = speed_mean_df.groupby(["TimeGroup", "New_Measurement"])["V_mean"].transform(lambda s: s.std(ddof=0))
    speed_mean_df["cv"] = speed_mean_df["std_group"] / speed_mean_df["V_mean"]
    speed_mean_df["w"] = 1 / speed_mean_df["cv"]
    speed_mean_df["w*v"] = speed_mean_df["w"] * speed_mean_df["V_mean"]

    weighted_result = (
        speed_mean_df.groupby(["TimeGroup","New_Measurement"])
          .apply(lambda g: g["w*v"].sum() / g["w"].sum())
          .reset_index(name="Weighted_Avg_Speed")
    )

    return weighted_result

def save_to_excel(excel_df, folder_path, file_name, color=False):
        result_folder = os.path.join(folder_path, "해상도+모형식 수정_260728")
        os.makedirs(result_folder, exist_ok=True)
        excel_file_name = f"{file_name}.xlsx"
        excel_file_path = os.path.join(result_folder, excel_file_name)

        if color:
            styled = excel_df.style.applymap(excel_color)
            styled.to_excel(excel_file_path, engine="openpyxl")
        else:
            excel_df.to_excel(excel_file_path, index=True)

        print(f"{excel_file_name} 생성 완료")

def z_to_score(z, z_min, z_max):
    if 1.645 <= z <= z_max:
        return 50 + ((95 + 5 * ((z - 1.645) / (z_max - 1.645))) * 0.5)
    elif 1.282 <= z < 1.645:
        return 50 + ((90 + 5 * ((z - 1.282) / (1.645 - 1.282))) * 0.5)
    elif 1.038 <= z < 1.282:
        return 50 + ((85 + 5 * ((z - 1.038) / (1.282 - 1.038))) * 0.5)
    elif 0.842 <= z < 1.038:
        return 50 + ((80 + 5 * ((z - 0.842) / (1.038 - 0.842))) * 0.5)
    elif 0.676 <= z < 0.842:
        return 50 + ((75 + 5 * ((z - 0.676) / (0.842 - 0.676))) * 0.5)
    elif 0.526 <= z < 0.676:
        return 50 + ((70 + 5 * ((z - 0.526) / (0.676 - 0.526))) * 0.5)
    elif 0.387 <= z < 0.526:
        return 50 + ((65 + 5 * ((z - 0.387) / (0.526 - 0.387))) * 0.5)
    elif 0.255 <= z < 0.387:
        return 50 + ((60 + 5 * ((z - 0.255) / (0.387 - 0.255))) * 0.5)
    elif -0.255 <= z < 0.255:
        return 50 + ((40 + 5 * ((z + 0.255) / (0.255 + 0.255))) * 0.5)
    elif -0.387 <= z < -0.255:
        return 50 + ((35 + 5 * ((z + 0.387) / (-0.255 + 0.387))) * 0.5)
    elif -0.526 <= z < -0.387:
        return 50 + ((30 + 5 * ((z + 0.526) / (-0.387 + 0.526))) * 0.5)
    elif -0.676 <= z < -0.526:
        return 50 + ((25 + 5 * ((z + 0.676) / (-0.676 + 0.842))) * 0.5)
    elif -0.842 <= z < -0.676:
        return 50 + ((20 + 5 * ((z + 0.842) / (-0.676 + 0.842))) * 0.5)
    elif -1.038 <= z < -0.842:
        return 50 + ((15 + 5 * ((z + 1.038) / (-0.842 + 1.038))) * 0.5)
    elif -1.282 <= z < -1.038:
        return 50 + ((10 + 5 * ((z + 1.282) / (-1.038 + 1.282))) * 0.5)
    elif -1.645 <= z < -1.282:
        return 50 + ((5 + 5 * ((z + 1.645) / (-1.282 + 1.645))) * 0.5)
    elif z_min <= z < -1.645:
        return 50 + ((0 + 5 * ((z + z_min) / (-1.645 + z_min))) * 0.5)
    else:
        return np.nan

def get_upstream_detector(root, location):
    detector_no = None
    detector_link = None
    gradient = None

    rsa_lane = None
    rsa_pos = None

    # 초기 데이터
    best_pos = -1

    for rsa in root.findall(".//reducedSpeedArea"):
        if rsa.get("name") == location:

            rsa_lane = rsa.get("lane")
            rsa_pos = float(rsa.get("pos"))

            # 유고 지점과 가장 가까운 상류 검지기
            for dcp in root.findall(".//dataCollectionPoint"):
                if dcp.get("lane") == rsa_lane:
                    dcp_pos = float(dcp.get("pos"))
                    if rsa_pos >= dcp_pos >= best_pos:
                        best_pos = dcp_pos

                        # 검지기 번호 가공 10010 -> 10
                        detector_no = int(dcp.get("no")) % 1000 - up_dcp_pos
                        detector_link = detector_map.get(detector_no)


    if detector_no is None:
        print("링크 번호가 다름")
        best_pos = float("inf")

        for dcp in root.findall(".//dataCollectionPoint"):
            if dcp.get("lane") == rsa_lane:
                dcp_pos = float(dcp.get("pos"))
                if rsa_pos < dcp_pos < best_pos:
                    best_pos = dcp_pos
                    detector_no = int(dcp.get("no")) % 1000 - 1- up_dcp_pos
                    detector_link = detector_map.get(detector_no)

    for link in root.findall(".//link"):
        if int(link.get("no")) == detector_link:
            gradient = round(float(link.get("gradient")),4)
            break

    return detector_no, gradient

def calculate_logD(speed_avg, entry_avg, heavy_avg, stvm_avg):
    speed_df = speed_avg.copy()
    entry_df = entry_avg.copy()
    heavy_df = heavy_avg.copy()
    stvm_df = stvm_avg.copy()

    speed_after = speed_df[(speed_df["New_Measurement"] == incident_measurement) & (speed_df["StartTime"] >= acc_start_time)].sort_values("StartTime").reset_index(drop=True)
    speed_after["is_congested"] = speed_after["V_mean"] <= Vc
    T2 = None


    for i in range(len(speed_after) - continuous_n + 1):

        if speed_after.loc[i:i + continuous_n - 1, "is_congested"].all():
            T2 = speed_after.loc[i + continuous_n -1 , "EndTime"]
            break

    if T2 is None:
        dc = np.nan
    else:
        dc = (T2 - acc_start_time) / 60
        if dc == 0:
            dc = np.nan
    print("dc : ", dc)
    display("speed_after : ", speed_after)

    el = lane - acc_lane

    before_group = f"{acc_start_time-sec_time}~{acc_start_time}"
    after_group = f"{acc_start_time}~{acc_start_time+sec_time}"

    s_before = entry_df.loc[(entry_df["TimeGroup"] == before_group) & (entry_df["New_Measurement"] == incident_measurement), "Phi_진입"].iloc[0]

    hv = heavy_df.loc[(heavy_df["TimeGroup"] == after_group) & (heavy_df["New_Measurement"] == incident_measurement), "rate"].iloc[0]

    stvm_before = stvm_df.loc[(stvm_df["TimeGroup"] == before_group) & (stvm_df["New_Measurement"] == incident_measurement),"STVM"].iloc[0]
    stvm_after = stvm_df.loc[(stvm_df["TimeGroup"] == after_group) & (stvm_df["New_Measurement"] == incident_measurement), "STVM"].iloc[0]

    log_dc_df = pd.DataFrame({
        # 종속 변수
        "Dc" : dc,
        "log_Dc" : np.log(dc),

        # 구조, 운영 변수
        "EL": el,
        "T": (acc_finish_time - acc_start_time)/60, # 분 단위
        "S_before": s_before,
        "HV": hv,
        "G": lane_gradient,

        # 교통류 반응 변수
        "STVM": stvm_before,
        "Delta_STVM": stvm_after - stvm_before,

    }, index=[0])
    return log_dc_df

def centralization_log_d(df):
    df = df.copy()
    means = df[["EL", "STVM", "Delta_STVM", "S_before", "HV", "G"]].mean(numeric_only=True)

    df["EL_c"] = df["EL"] - means["EL"]
    df["I_EL"] = (df["EL"] > 0).astype(int)
    df["T_c"] = df["T"]
    df["S_c"] = df["S_before"] - means["S_before"]
    df["HV_c"] = df["HV"] - means["HV"]
    df["G_c"] = df["G"] - means["G"]
    df["S_c**2"] = df["S_c"] ** 2
    df["STVM_c"] = df["STVM"] - means["STVM"]
    df["Delta_STVM_c"] = df["Delta_STVM"] - means["Delta_STVM"]
    df["EL_c*S_c"] = df["EL_c"] * df["S_c"]
    df["HV_c*G_c"] = df["HV_c"] * df["G_c"]

    df["I_EL_S"] = df["I_EL"] * df["S_c"]

    result_df = df[["Dc", "log_Dc","EL_c", "I_EL", "T_c", "S_c", "HV_c", "G_c", "S_c**2", "STVM_c", "Delta_STVM_c", "EL_c*S_c", "HV_c*G_c", "I_EL_S"]]

    result_df = result_df.round(3)
    return result_df


def complete_time_measurement(df, value_cols, measurements=None):
    df = df.copy()

    # 전체 시간대 생성
    full_time = pd.DataFrame({
        "StartTime": np.arange(start_interval, end_interval, sec_time)
    })
    full_time["EndTime"] = full_time["StartTime"] + sec_time
    full_time["TimeGroup"] = (
        full_time["StartTime"].astype(str)
        + "~"
        + full_time["EndTime"].astype(str)
    )

    # 전체 검지기 목록
    if measurements is None:
        measurements = sorted(df["New_Measurement"].dropna().unique())

    measurement_df = pd.DataFrame({
        "New_Measurement": measurements
    })

    full_index = (
        full_time.assign(key=1)
        .merge(measurement_df.assign(key=1), on="key")
        .drop(columns="key")
    )

    # 누락된 TimeGroup × New_Measurement 생성
    df = full_index.merge(
        df,
        on=["TimeGroup", "New_Measurement"],
        how="left"
    )

    # 값 없는 부분 0 처리
    for col in value_cols:
        if col in df.columns:
            df[col] = df[col].fillna(0)

    df = sort_ascending(df)

    return df
###################################################################################################################

senario_df = pd.read_csv(senario_path, encoding="cp949")

tree = ET.parse(inpx_path)
root = tree.getroot()


# 검지기 정보 미리 로드
detector_map = {}

for dcp in root.findall(".//dataCollectionPoint"):

    # 검지기 번호 (10010 → 10)
    detector_no = int(dcp.get("no")) % 1000

    # 링크 번호 ("23 1" → 23)
    detector_link = int(dcp.get("lane").split()[0])

    # 딕셔너리에 저장
    detector_map[detector_no] = detector_link


folder_path = path
parquet_list = sorted([file for file in os.listdir(folder_path) if file.endswith(".parquet")])

for sec_time in sec_time_list:

    revision_time = 3600 / sec_time

    for up_dcp_pos in up_dcp_pos_list:

        gradient_list = []

        print(f"\n===== 집계시간 {sec_time}초 / 상류검지기 {up_dcp_pos} =====")

        for cdx, continuous_num in enumerate(continuous_list):
            continuous_n = int(continuous_num / sec_time)
            log_d_df_list = []
            vc_result_list = []
            for idx, start in enumerate(range(0, len(parquet_list), num_mer)):
                print(f"============ idx={idx}, start={start} ============")

                row = senario_df.iloc[idx]

                # 기존 차로 수
                lane = row["lane_count"]

                # 유고 차로 수
                acc_lane = row["lane_closure_count"]

                # 유고 종료 시간
                acc_finish_time = acc_start_time + row["incident_duration_min"] * 60

                # 유고 지점
                incident_location = row["location_name"]
                locations = [x.strip() for x in incident_location.split(",")] # [본선1, 본선2]
                location = locations[0]
                incident_measurement, lane_gradient = get_upstream_detector(root, location)

                gradient_list.append((incident_measurement, lane_gradient))

                batch_files = parquet_list[start:start + num_mer]

                print("Vc : ", Vc)
                print(
                     f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] "
                    f"입력값 | 교통량={row['base_main_in_vph']}, 기존 차로수={lane}, 유고 차로수={acc_lane}, 유고지속시간={row['incident_duration_min']}, 유고지점={incident_location}, 검지기={incident_measurement}, lane_gradient={lane_gradient}"
                    )

                i = start // num_mer

                speed_list = []
                density_list = []
                heavy_list = []
                entry_list = []
                rfr_list_all = []
                normality_list_all = []
                stvm_list = []
                vc_speed_list = []

                for index, mer_file in enumerate(batch_files):
                    print("작업파일 :", mer_file)

                    file_path = os.path.join(folder_path, mer_file)
                    df = pd.read_parquet(file_path)

                    # 컬럼 내부 데이터 정수형 변환
                    df = df.apply(pd.to_numeric, errors="coerce")

                    original_df = df[(df["t(Entry)"] != -1.00)].reset_index(drop=True)

                    # 불필요 컬럼 제거
                    original_df.drop(columns=["b[m/s2]", "tQueue", "Occ", "Pers"], inplace=True, errors="ignore")

                    # 차로 통합을 위한 컬럼
                    original_df["New_Measurement"] = original_df["Measurem."] % 1000

                    # 원본 데이터 vc 도출
                    vc_speed_list.append(original_df[["New_Measurement", "t(Entry)", "v[km/h]"]])

                    # 5분단위 집계
                    bins = np.arange(start_interval, end_interval+1, sec_time)
                    labels = [f"{start}~{start+sec_time}" for start in bins[:-1]]  # 구간 라벨링

                    # 구간 나누기 및 컬럼 추가
                    original_df["TimeGroup"] = pd.cut(original_df["t(Entry)"], bins=bins, labels=labels, right=False)

                    original_df = original_df[original_df["TimeGroup"].notna()].copy()
                    original_df["TimeGroup"] = original_df["TimeGroup"].astype(str)

                    # 가감속 차로 부분 검지기 제거
                    #original_df = original_df[~original_df["Measurem."].between(30000, 39999)]

                    # 속도변화율
                    speed_df = speed_mean(original_df)
                    speed_list.append(speed_df)


                    # 밀도변화율
                    density_df = density_mean(speed_df)
                    density_list.append(density_df)

                    # 중차량 혼입률
                    heavy_df = heavy_rate(original_df)
                    heavy_list.append(heavy_df)

                    # 동적 포화도
                    entry_saturation_df = entry_saturation(original_df)
                    entry_list.append(entry_saturation_df)

                    # 램프 간섭 영향률
                    rfr_df = rfr_rate(original_df)
                    rfr_list_all.append(rfr_df)

                    # 진출 원활율
                    normality_df = output_normality(original_df)
                    normality_list_all.append(normality_df)

                    # STVM 계산
                    stvm_df = calculate_stvm(speed_df, density_df, heavy_df, entry_saturation_df, rfr_df, normality_df)
                    stvm_list.append(stvm_df)

                print("시드 평균 계산 중...")

                merged_speed = pd.concat(speed_list)
                merged_density = pd.concat(density_list)
                merged_heavy = pd.concat(heavy_list)
                merged_entry = pd.concat(entry_list)
                merged_rfr = pd.concat(rfr_list_all)
                merged_normality = pd.concat(normality_list_all)
                merged_stvm = pd.concat(stvm_list)
                vc_speed_df = pd.concat(vc_speed_list)

                # 각 지표 평균
                speed_avg = (
                    merged_speed
                    .groupby(["StartTime", "EndTime", "TimeGroup", "New_Measurement"])
                    [["V_mean", "delta_V"]]
                    .mean()
                    .reset_index()
                )

                density_avg = (
                    merged_density
                    .groupby(["StartTime","TimeGroup", "New_Measurement"])
                    [["delta_K"]]
                    .mean()
                    .reset_index()
                )

                heavy_avg = (
                    merged_heavy
                    .groupby(["StartTime", "TimeGroup", "New_Measurement"])
                    [["rate"]]
                    .mean()
                    .reset_index()
                )

                entry_avg = (
                    merged_entry
                    .groupby(["StartTime", "TimeGroup", "New_Measurement"])
                    [["Phi_진입"]]
                    .mean()
                    .reset_index()
                )

                rfr_avg = (
                    merged_rfr
                    .groupby(["StartTime", "TimeGroup", "New_Measurement"])
                    [["RFR"]]
                    .mean()
                    .reset_index()
                )

                normality_avg = (
                    merged_normality
                    .groupby(["StartTime", "TimeGroup", "New_Measurement"])
                    [["F(outrate)"]]
                    .mean()
                    .reset_index()
                )

                stvm_avg = (
                    merged_stvm
                    .groupby(["TimeGroup", "New_Measurement"], sort=False)
                    .mean(numeric_only=True)
                    .reset_index()
                )


                #save_to_excel(speed_avg, folder_path, "속도변화량", i)
                #save_to_excel(density_avg, folder_path, "밀도변화량", i)
                #save_to_excel(stvm_avg, folder_path, "STVM", i)

                # Z-Score 계산
                #z_score_df = calculate_z_score(stvm_avg)
                #save_to_excel(z_score_df, folder_path, f"환산점수", i)

                # STVM 피봇
                #stvm_pivot_df = pivot_table(stvm_avg, "STVM", preprocess=modify_frame)
                #save_to_excel(stvm_pivot_df, folder_path, f"지표합산값", i, color=True)

                # 속도값 피봇
                #speed_pivot_df = pivot_table(speed_avg, "V_mean", preprocess=modify_frame)
                #save_to_excel(speed_pivot_df, folder_path, "속도 피봇", i, color=True)

                # 임계 붕괴 시간 추정 모형
                log_d_df = calculate_logD(speed_avg, entry_avg, heavy_avg, stvm_avg)
                #display("log_d_df : ", log_d_df)
                log_d_df_list.append(log_d_df)
                #save_to_excel(log_d_df, folder_path, "임계추정모형", i)

                # 지표별 구성값(속도변화값)
                #speed_pivot_df = pivot_table(speed_df, "delta_V", preprocess=modify_frame)
                #save_to_excel(speed_pivot_df, folder_path, "속도변화값", i)

                # 지표별 구성값(밀도변화값)
                #density_pivot_df = pivot_table(density_df, "delta_K", preprocess=modify_frame)
                #save_to_excel(density_pivot_df, folder_path, "밀도변화값", i)

                # 지표별 구성값(중차량혼입률)
                #heavy_pivot_df = pivot_table(heavy_df, "rate", preprocess=modify_frame)
                #save_to_excel(heavy_pivot_df, folder_path, "중차량혼입률", i)

                # 지표별 구성값(동적포화도)
                #entry_saturation_pivot_df = pivot_table(entry_saturation_df, "Phi_진입", preprocess=modify_frame)
                #save_to_excel(entry_saturation_pivot_df, folder_path, "동적포화도", i)

                # 지표별 구성값(램프 간섭 영향률)
                #rfr_pivot_df = pivot_table(rfr_df, "RFR", preprocess=modify_frame)
                #save_to_excel(rfr_pivot_df, folder_path, "램프간섭영향률", i)

                # 지표별 구성값(진출 원활률)
                #normality_pivot_df = pivot_table(normality_df, "F(outrate)", preprocess=modify_frame)
                #save_to_excel(normality_pivot_df, folder_path, "진출원활률", i)

                # 메모리 정리
                #del df, original_df, speed_df, density_df, heavy_df, entry_saturation_df, rfr_df, normality_df, stvm_df, z_score_df
                gc.collect()

            log_d_df_all = pd.concat(log_d_df_list, ignore_index=True)
            final_log_d = centralization_log_d(log_d_df_all)
            final_log_d = final_log_d.fillna("NA")
            save_to_excel(final_log_d, folder_path, f"임계연속시간_본선부_구간2_{sec_time}초_{150 + (up_dcp_pos - 1) * 100}m")
            #gradient_df = pd.DataFrame(gradient_list, columns=["검지기 번호", "종단경사"])
            #save_to_excel(gradient_df, folder_path, "종단경사", 0)
            #save_to_excel(vc_result_df, folder_path, "임계속도", 0)

===== 집계시간 10초 / 상류검지기 1 =====
============ idx=0, start=0 ============
Vc :  53.7
[2026-07-28 11:25:10] 입력값 | 교통량=1444, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부64-1, 검지기=94, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_001.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_002.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_003.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,94,88.233333,-0.111526,False
1,3610,3620,3610~3620,94,82.730556,-0.253112,False
2,3620,3630,3620~3630,94,55.133333,-0.127008,False
3,3630,3640,3630~3640,94,80.675000,-0.243247,False
4,3640,3650,3640~3650,94,79.607619,-0.245355,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,94,85.475000,-0.006343,False
956,13160,13170,13160~13170,94,84.446429,0.001082,False
957,13170,13180,13170~13180,94,85.322222,-0.017067,False
958,13180,13190,13180~13190,94,57.195000,-0.006893,False
959,13190,13200,13190~13200,94,86.416667,-0.003807,False

============ idx=1, start=3 ============
Vc :  53.7
[2026-07-28 11:26:05] 입력값 | 교통량=1619, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부48-1, 검지기=78, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_004.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_005.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_006.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,78,85.205952,-0.044476,False
1,3610,3620,3610~3620,78,85.137037,-0.122978,False
2,3620,3630,3620~3630,78,81.749206,-0.581345,False
3,3630,3640,3630~3640,78,80.626667,-0.211336,False
4,3640,3650,3640~3650,78,81.679167,-0.183467,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,78,85.958889,-0.005139,False
956,13160,13170,13160~13170,78,86.297727,-0.000764,False
957,13170,13180,13170~13180,78,55.975000,0.009651,False
958,13180,13190,13180~13190,78,86.957540,-0.004706,False
959,13190,13200,13190~13200,78,85.943333,-0.002642,False

============ idx=2, start=6 ============
Vc :  53.7
[2026-07-28 11:27:00] 입력값 | 교통량=1118, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부65-1,본선부65-2, 검지기=95, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_007.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_008.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_009.parquet
시드 평균 계산 중...
dc :  4.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,95,82.750000,-0.314140,False
1,3610,3620,3610~3620,95,79.172222,-0.402738,False
2,3620,3630,3620~3630,95,78.394444,-0.517760,False
3,3630,3640,3630~3640,95,82.016667,-0.719117,False
4,3640,3650,3640~3650,95,55.027778,-0.537459,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,95,57.283333,-0.001376,False
956,13160,13170,13160~13170,95,86.549444,0.015289,False
957,13170,13180,13170~13180,95,86.996667,-0.017528,False
958,13180,13190,13180~13190,95,87.981667,-0.024925,False
959,13190,13200,13190~13200,95,85.722222,0.010788,False

============ idx=3, start=9 ============
Vc :  53.7
[2026-07-28 11:27:50] 입력값 | 교통량=1741, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부65-1, 검지기=95, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_010.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_011.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_012.parquet
시드 평균 계산 중...
dc :  9.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,95,84.805556,-0.123537,False
1,3610,3620,3610~3620,95,83.227778,-0.092971,False
2,3620,3630,3620~3630,95,81.611667,-0.140263,False
3,3630,3640,3630~3640,95,79.516667,-0.282958,False
4,3640,3650,3640~3650,95,77.926190,-0.550512,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,95,85.105556,-0.003148,False
956,13160,13170,13160~13170,95,86.909524,-0.005629,False
957,13170,13180,13170~13180,95,86.483333,0.009806,False
958,13180,13190,13180~13190,95,89.901667,0.013070,False
959,13190,13200,13190~13200,95,84.377778,0.022243,False

============ idx=4, start=12 ============
Vc :  53.7
[2026-07-28 11:28:53] 입력값 | 교통량=1785, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부61-1, 검지기=91, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_013.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_014.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_015.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,91,84.463889,-0.188716,False
1,3610,3620,3610~3620,91,81.058333,-0.106787,False
2,3620,3630,3620~3630,91,78.516667,-0.277286,False
3,3630,3640,3630~3640,91,80.283148,-0.210699,False
4,3640,3650,3640~3650,91,77.589394,-0.201706,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,91,84.433333,0.005772,False
956,13160,13170,13160~13170,91,84.034127,0.020106,False
957,13170,13180,13170~13180,91,84.669444,-0.041521,False
958,13180,13190,13180~13190,91,86.266667,-0.001540,False
959,13190,13200,13190~13200,91,84.282619,-0.002870,False

============ idx=5, start=15 ============
Vc :  53.7
[2026-07-28 11:30:02] 입력값 | 교통량=1104, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부79-1, 검지기=109, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_016.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_017.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_018.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,109,84.933333,-0.168914,False
1,3610,3620,3610~3620,109,82.638889,-0.038580,False
2,3620,3630,3620~3630,109,83.328704,-0.039666,False
3,3630,3640,3630~3640,109,82.003333,-0.077329,False
4,3640,3650,3640~3650,109,79.550000,-0.245408,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,109,85.216667,-0.001668,False
956,13160,13170,13160~13170,109,56.633333,0.002379,False
957,13170,13180,13170~13180,109,28.333333,-0.333333,True
958,13180,13190,13180~13190,109,57.433333,0.002140,False
959,13190,13200,13190~13200,109,84.409921,0.015655,False

============ idx=6, start=18 ============
Vc :  53.7
[2026-07-28 11:31:08] 입력값 | 교통량=836, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부68-1,본선부68-2, 검지기=98, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_019.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_020.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_021.parquet
시드 평균 계산 중...
dc :  5.333333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,98,79.916667,-0.399163,False
1,3610,3620,3610~3620,98,52.816667,-0.261984,True
2,3620,3630,3620~3630,98,53.533333,-0.298004,True
3,3630,3640,3630~3640,98,55.655556,-0.666667,False
4,3640,3650,3640~3650,98,81.133333,-0.487258,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,98,86.177778,-0.323246,False
956,13160,13170,13160~13170,98,85.411111,0.003981,False
957,13170,13180,13170~13180,98,58.200000,-0.666667,False
958,13180,13190,13180~13190,98,63.133333,-0.055135,False
959,13190,13200,13190~13200,98,89.383333,-0.331684,False

============ idx=7, start=21 ============
Vc :  53.7
[2026-07-28 11:32:08] 입력값 | 교통량=1308, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부56-1, 검지기=86, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_022.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_023.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_024.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,86,84.452778,-0.384808,False
1,3610,3620,3610~3620,86,27.633333,-0.062525,True
2,3620,3630,3620~3630,86,82.305397,-0.019682,False
3,3630,3640,3630~3640,86,83.488889,-0.195934,False
4,3640,3650,3640~3650,86,55.166667,-0.125691,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,86,58.994444,-0.020392,False
956,13160,13170,13160~13170,86,59.116667,0.030812,False
957,13170,13180,13170~13180,86,87.238889,-0.342175,False
958,13180,13190,13180~13190,86,86.972222,0.013264,False
959,13190,13200,13190~13200,86,89.425000,-0.003439,False

============ idx=8, start=24 ============
Vc :  53.7
[2026-07-28 11:33:14] 입력값 | 교통량=1749, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부71-1, 검지기=101, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_025.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_026.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_027.parquet
시드 평균 계산 중...
dc :  9.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,101,81.355000,-0.068876,False
1,3610,3620,3610~3620,101,52.611111,-0.117803,True
2,3620,3630,3620~3630,101,80.319444,-0.368747,False
3,3630,3640,3630~3640,101,79.983333,-0.267265,False
4,3640,3650,3640~3650,101,80.107143,-0.240365,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,101,85.237273,0.000354,False
956,13160,13170,13160~13170,101,87.600000,-0.018259,False
957,13170,13180,13170~13180,101,91.911111,0.014583,False
958,13180,13190,13180~13190,101,89.488889,0.007519,False
959,13190,13200,13190~13200,101,86.067778,0.001000,False

============ idx=9, start=27 ============
Vc :  53.7
[2026-07-28 11:34:23] 입력값 | 교통량=1408, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부60-1, 검지기=90, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_028.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_029.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_030.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,90,85.100000,-0.369268,False
1,3610,3620,3610~3620,90,84.597222,-0.220585,False
2,3620,3630,3620~3630,90,82.035714,-0.117218,False
3,3630,3640,3630~3640,90,79.333333,-0.170120,False
4,3640,3650,3640~3650,90,55.845714,-0.054707,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,90,85.344444,-0.002624,False
956,13160,13170,13160~13170,90,56.766667,0.002368,False
957,13170,13180,13170~13180,90,86.380000,-0.321845,False
958,13180,13190,13180~13190,90,85.851852,0.008505,False
959,13190,13200,13190~13200,90,88.291111,0.004543,False

============ idx=10, start=30 ============
링크 번호가 다름
Vc :  53.7
[2026-07-28 11:35:31] 입력값 | 교통량=1315, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부53-1,본선부53-2, 검지기=83, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_031.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_032.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_033.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,83,81.566667,-0.349352,False
1,3610,3620,3610~3620,83,78.916667,-0.418738,False
2,3620,3630,3620~3630,83,78.654167,-0.481363,False
3,3630,3640,3630~3640,83,75.269444,-0.602337,False
4,3640,3650,3640~3650,83,69.337778,-0.838935,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,83,85.650000,-0.039330,False
956,13160,13170,13160~13170,83,56.462500,0.018931,False
957,13170,13180,13170~13180,83,89.394444,-0.041853,False
958,13180,13190,13180~13190,83,86.488889,0.016192,False
959,13190,13200,13190~13200,83,92.133333,-0.020217,False

============ idx=11, start=33 ============
Vc :  53.7
[2026-07-28 11:36:32] 입력값 | 교통량=1722, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부55-1, 검지기=85, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_034.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_035.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_036.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,85,83.308333,-0.137563,False
1,3610,3620,3610~3620,85,83.651667,-0.111492,False
2,3620,3630,3620~3630,85,82.513889,-0.177224,False
3,3630,3640,3630~3640,85,81.395000,-0.210427,False
4,3640,3650,3640~3650,85,78.726190,-0.213352,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,85,84.155556,-0.316518,False
956,13160,13170,13160~13170,85,84.745455,-0.008019,False
957,13170,13180,13170~13180,85,84.437778,0.016549,False
958,13180,13190,13180~13190,85,86.898413,-0.006212,False
959,13190,13200,13190~13200,85,86.068889,-0.005419,False

============ idx=12, start=36 ============
Vc :  53.7
[2026-07-28 11:37:44] 입력값 | 교통량=796, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부66-1,본선부66-2, 검지기=96, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_037.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_038.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_039.parquet
시드 평균 계산 중...
dc :  5.666666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,96,83.350000,-0.244897,False
1,3610,3620,3610~3620,96,81.827778,-0.414123,False
2,3620,3630,3620~3630,96,80.844444,-0.416894,False
3,3630,3640,3630~3640,96,83.766667,-0.509186,False
4,3640,3650,3640~3650,96,81.636667,-0.679025,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,96,34.966667,-0.040568,True
956,13160,13170,13160~13170,96,86.333333,-0.676651,False
957,13170,13180,13170~13180,96,84.866667,0.005226,False
958,13180,13190,13180~13190,96,86.011905,-0.006648,False
959,13190,13200,13190~13200,96,93.611905,-0.067577,False

============ idx=13, start=39 ============
Vc :  53.7
[2026-07-28 11:38:41] 입력값 | 교통량=1233, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부58-1, 검지기=88, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_040.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_041.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_042.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,88,85.140000,-0.103549,False
1,3610,3620,3610~3620,88,84.163889,-0.143322,False
2,3620,3630,3620~3630,88,56.491667,-0.025326,False
3,3630,3640,3630~3640,88,81.980357,-0.020572,False
4,3640,3650,3640~3650,88,53.613333,-0.192280,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,88,84.893333,-0.006699,False
956,13160,13170,13160~13170,88,85.844444,-0.324333,False
957,13170,13180,13170~13180,88,86.338889,-0.016055,False
958,13180,13190,13180~13190,88,89.950000,-0.001918,False
959,13190,13200,13190~13200,88,87.791667,-0.009185,False

============ idx=14, start=42 ============
Vc :  53.7
[2026-07-28 11:39:49] 입력값 | 교통량=1362, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부70-1, 검지기=100, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_043.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_044.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_045.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,100,81.898413,-0.064730,False
1,3610,3620,3610~3620,100,79.531746,-0.214155,False
2,3620,3630,3620~3630,100,78.608333,-0.265432,False
3,3630,3640,3630~3640,100,79.358333,-0.199024,False
4,3640,3650,3640~3650,100,80.088095,-0.315946,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,100,85.923810,-0.001440,False
956,13160,13170,13160~13170,100,85.194444,-0.000759,False
957,13170,13180,13170~13180,100,85.501587,-0.010411,False
958,13180,13190,13180~13190,100,85.055556,0.001954,False
959,13190,13200,13190~13200,100,86.658929,-0.002953,False

============ idx=15, start=45 ============
Vc :  53.7
[2026-07-28 11:40:58] 입력값 | 교통량=1531, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부61-1,본선부61-2, 검지기=91, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_046.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_047.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_048.parquet
시드 평균 계산 중...
dc :  4.333333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,91,83.023333,-0.392769,False
1,3610,3620,3610~3620,91,81.117857,-0.424316,False
2,3620,3630,3620~3630,91,81.021905,-0.495417,False
3,3630,3640,3630~3640,91,73.719444,-0.650433,False
4,3640,3650,3640~3650,91,67.722727,-0.860137,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,91,89.396667,-0.018849,False
956,13160,13170,13160~13170,91,85.805556,0.014614,False
957,13170,13180,13170~13180,91,83.670833,-0.012653,False
958,13180,13190,13180~13190,91,84.522222,-0.333624,False
959,13190,13200,13190~13200,91,85.583333,0.003569,False

============ idx=16, start=48 ============
Vc :  53.7
[2026-07-28 11:41:59] 입력값 | 교통량=563, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부52-1, 검지기=82, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_049.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_050.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_051.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,82,84.500000,-0.807434,False
1,3610,3620,3610~3620,82,55.711111,-0.055081,False
2,3620,3630,3620~3630,82,83.316667,-0.497237,False
3,3630,3640,3630~3640,82,82.166667,-0.373473,False
4,3640,3650,3640~3650,82,28.000000,-0.070238,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,82,56.300000,0.009385,False
956,13160,13170,13160~13170,82,27.700000,0.014039,True
957,13170,13180,13170~13180,82,56.360000,-0.326926,False
958,13180,13190,13180~13190,82,85.100000,-0.320031,False
959,13190,13200,13190~13200,82,86.111111,-0.330232,False

============ idx=17, start=51 ============
Vc :  53.7
[2026-07-28 11:43:00] 입력값 | 교통량=1586, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부49-1,본선부49-2, 검지기=79, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_052.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_053.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_054.parquet
시드 평균 계산 중...
dc :  4.333333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,79,81.831111,-0.533285,False
1,3610,3620,3610~3620,79,81.908333,-0.444533,False
2,3620,3630,3620~3630,79,79.921429,-0.531281,False
3,3630,3640,3630~3640,79,76.166667,-0.660286,False
4,3640,3650,3640~3650,79,74.273810,-0.831138,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,79,86.136111,-0.013607,False
956,13160,13170,13160~13170,79,85.200000,0.010337,False
957,13170,13180,13170~13180,79,87.941667,0.010642,False
958,13180,13190,13180~13190,79,82.237500,0.059132,False
959,13190,13200,13190~13200,79,87.367857,-0.070326,False

============ idx=18, start=54 ============
Vc :  53.7
[2026-07-28 11:44:02] 입력값 | 교통량=1424, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부82-1, 검지기=112, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_055.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_056.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_057.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,112,83.180000,-0.224275,False
1,3610,3620,3610~3620,112,52.755556,-0.175020,True
2,3620,3630,3620~3630,112,84.135000,-0.305386,False
3,3630,3640,3630~3640,112,79.062222,-0.246793,False
4,3640,3650,3640~3650,112,79.061111,-0.427167,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,112,83.930139,-0.005180,False
956,13160,13170,13160~13170,112,82.906373,0.035138,False
957,13170,13180,13170~13180,112,84.907778,-0.025010,False
958,13180,13190,13180~13190,112,86.337460,-0.015270,False
959,13190,13200,13190~13200,112,85.642222,-0.011394,False

============ idx=19, start=57 ============
Vc :  53.7
[2026-07-28 11:45:10] 입력값 | 교통량=1374, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부63-1, 검지기=93, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_058.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_059.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_060.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,93,85.573810,-0.058954,False
1,3610,3620,3610~3620,93,86.366667,-0.106632,False
2,3620,3630,3620~3630,93,83.834722,-0.039679,False
3,3630,3640,3630~3640,93,79.931944,-0.162368,False
4,3640,3650,3640~3650,93,77.838095,-0.483920,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,93,85.468254,-0.000526,False
956,13160,13170,13160~13170,93,91.805556,-0.050098,False
957,13170,13180,13170~13180,93,57.911111,0.004850,False
958,13180,13190,13180~13190,93,83.483333,-0.087003,False
959,13190,13200,13190~13200,93,83.995833,-0.295447,False

============ idx=20, start=60 ============
Vc :  53.7
[2026-07-28 11:46:22] 입력값 | 교통량=674, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부63-1,본선부63-2, 검지기=93, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_061.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_062.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_063.parquet
시드 평균 계산 중...
dc :  4.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,93,83.014444,-0.399323,False
1,3610,3620,3610~3620,93,82.783333,-0.442762,False
2,3620,3630,3620~3630,93,83.350000,-0.509813,False
3,3630,3640,3630~3640,93,82.386667,-0.683803,False
4,3640,3650,3640~3650,93,48.992857,-0.419721,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,93,58.816667,-0.021393,False
956,13160,13170,13160~13170,93,63.033333,0.005702,False
957,13170,13180,13170~13180,93,60.433333,-0.338725,False
958,13180,13190,13180~13190,93,28.185714,0.004111,True
959,13190,13200,13190~13200,93,56.566667,-0.322142,False

============ idx=21, start=63 ============
링크 번호가 다름
Vc :  53.7
[2026-07-28 11:47:18] 입력값 | 교통량=1650, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부53-1, 검지기=83, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_064.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_065.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_066.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,83,82.069444,-0.079890,False
1,3610,3620,3610~3620,83,82.041667,-0.194503,False
2,3620,3630,3620~3630,83,77.071667,-0.287694,False
3,3630,3640,3630~3640,83,79.544444,-0.297693,False
4,3640,3650,3640~3650,83,77.188889,-0.239023,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,83,86.430952,-0.024059,False
956,13160,13170,13160~13170,83,85.956349,0.027858,False
957,13170,13180,13170~13180,83,85.000000,0.001927,False
958,13180,13190,13180~13190,83,85.743611,-0.016274,False
959,13190,13200,13190~13200,83,85.425000,-0.010085,False

============ idx=22, start=66 ============
Vc :  53.7
[2026-07-28 11:48:28] 입력값 | 교통량=1729, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부72-1, 검지기=102, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_067.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_068.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_069.parquet
시드 평균 계산 중...
dc :  20.166666666666668

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,102,84.716667,-0.179024,False
1,3610,3620,3610~3620,102,83.139048,-0.115709,False
2,3620,3630,3620~3630,102,79.695000,-0.204106,False
3,3630,3640,3630~3640,102,80.024074,-0.340114,False
4,3640,3650,3640~3650,102,81.211111,-0.281600,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,102,85.505556,0.000830,False
956,13160,13170,13160~13170,102,84.705833,0.006338,False
957,13170,13180,13170~13180,102,84.820707,0.004552,False
958,13180,13190,13180~13190,102,85.791667,-0.000486,False
959,13190,13200,13190~13200,102,85.795238,0.005587,False

============ idx=23, start=69 ============
Vc :  53.7
[2026-07-28 11:49:40] 입력값 | 교통량=721, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부59-1,본선부59-2, 검지기=89, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_070.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_071.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_072.parquet
시드 평균 계산 중...
dc :  5.333333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,89,82.878333,-0.813647,False
1,3610,3620,3610~3620,89,55.600000,-0.281974,False
2,3620,3630,3620~3630,89,26.566667,-0.133417,True
3,3630,3640,3630~3640,89,82.811111,-0.429081,False
4,3640,3650,3640~3650,89,51.850000,-0.291532,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,89,60.638095,0.003413,False
956,13160,13170,13160~13170,89,57.433333,-0.333724,False
957,13170,13180,13170~13180,89,57.083333,-0.002911,False
958,13180,13190,13180~13190,89,57.394444,-0.004798,False
959,13190,13200,13190~13200,89,82.933333,-0.414669,False

============ idx=24, start=72 ============
Vc :  53.7
[2026-07-28 11:50:34] 입력값 | 교통량=1648, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부50-1, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_073.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_074.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_075.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,83.256667,-0.215539,False
1,3610,3620,3610~3620,80,80.469048,-0.105416,False
2,3620,3630,3620~3630,80,82.424444,-0.200909,False
3,3630,3640,3630~3640,80,79.116667,-0.244208,False
4,3640,3650,3640~3650,80,83.075556,-0.295735,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,85.577778,0.007780,False
956,13160,13170,13160~13170,80,85.131111,0.008405,False
957,13170,13180,13170~13180,80,87.491111,0.001184,False
958,13180,13190,13180~13190,80,86.581111,-0.012537,False
959,13190,13200,13190~13200,80,85.155556,0.043634,False

============ idx=25, start=75 ============
Vc :  53.7
[2026-07-28 11:51:42] 입력값 | 교통량=869, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부52-1, 검지기=82, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_076.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_077.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_078.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,82,85.013889,-0.174475,False
1,3610,3620,3610~3620,82,85.300000,-0.361359,False
2,3620,3630,3620~3630,82,82.336667,-0.157985,False
3,3630,3640,3630~3640,82,81.371111,-0.174610,False
4,3640,3650,3640~3650,82,50.100000,-0.113965,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,82,85.104762,0.042151,False
956,13160,13170,13160~13170,82,85.188889,-0.318755,False
957,13170,13180,13170~13180,82,59.077778,-0.010060,False
958,13180,13190,13180~13190,82,87.880000,-0.340966,False
959,13190,13200,13190~13200,82,87.650000,0.015398,False

============ idx=26, start=78 ============
Vc :  53.7
[2026-07-28 11:52:47] 입력값 | 교통량=1320, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부70-1,본선부70-2, 검지기=100, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_079.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_080.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_081.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,100,81.127778,-0.319301,False
1,3610,3620,3610~3620,100,74.808333,-0.399084,False
2,3620,3630,3620~3630,100,73.491111,-0.577426,False
3,3630,3640,3630~3640,100,53.394444,-0.574965,True
4,3640,3650,3640~3650,100,77.416667,-0.946544,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,100,58.792857,0.018130,False
956,13160,13170,13160~13170,100,28.941667,-0.005855,True
957,13170,13180,13170~13180,100,83.133333,0.009269,False
958,13180,13190,13180~13190,100,85.111667,-0.658155,False
959,13190,13200,13190~13200,100,57.016667,-0.006153,False

============ idx=27, start=81 ============
Vc :  53.7
[2026-07-28 11:53:49] 입력값 | 교통량=1359, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부57-1, 검지기=87, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_082.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_083.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_084.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,87,83.833333,-0.072666,False
1,3610,3620,3610~3620,87,82.522222,-0.090574,False
2,3620,3630,3620~3630,87,81.038889,-0.170444,False
3,3630,3640,3630~3640,87,82.206667,-0.334714,False
4,3640,3650,3640~3650,87,52.827778,-0.291504,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,87,86.911111,-0.018517,False
956,13160,13170,13160~13170,87,85.977778,-0.003656,False
957,13170,13180,13170~13180,87,55.071429,0.018050,False
958,13180,13190,13180~13190,87,85.903175,-0.022467,False
959,13190,13200,13190~13200,87,84.788333,0.023823,False

============ idx=28, start=84 ============
Vc :  53.7
[2026-07-28 11:54:58] 입력값 | 교통량=822, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부82-1, 검지기=112, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_085.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_086.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_087.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,112,55.150000,-0.146189,False
1,3610,3620,3610~3620,112,55.244444,-0.404643,False
2,3620,3630,3620~3630,112,77.537500,-0.535988,False
3,3630,3640,3630~3640,112,80.300000,-0.253814,False
4,3640,3650,3640~3650,112,54.933333,-0.225225,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,112,85.608333,-0.005642,False
956,13160,13170,13160~13170,112,89.900000,-0.011738,False
957,13170,13180,13170~13180,112,93.650000,0.002060,False
958,13180,13190,13180~13190,112,57.472222,0.018220,False
959,13190,13200,13190~13200,112,84.666667,0.028836,False

============ idx=29, start=87 ============
링크 번호가 다름
Vc :  53.7
[2026-07-28 11:56:01] 입력값 | 교통량=1405, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부53-1,본선부53-2, 검지기=83, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_088.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_089.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_090.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,83,83.075000,-0.259344,False
1,3610,3620,3610~3620,83,77.408333,-0.373238,False
2,3620,3630,3620~3630,83,81.434259,-0.494319,False
3,3630,3640,3630~3640,83,70.557407,-0.539428,False
4,3640,3650,3640~3650,83,37.803333,-0.542231,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,83,84.697778,-0.016765,False
956,13160,13170,13160~13170,83,88.577778,0.010467,False
957,13170,13180,13170~13180,83,86.328889,-0.008464,False
958,13180,13190,13180~13190,83,90.726667,-0.040612,False
959,13190,13200,13190~13200,83,87.822778,0.038944,False

============ idx=30, start=90 ============
Vc :  53.7
[2026-07-28 11:57:04] 입력값 | 교통량=1714, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부50-1, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_091.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_092.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_093.parquet
시드 평균 계산 중...
dc :  nan

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,82.863889,-0.204105,False
1,3610,3620,3610~3620,80,84.900000,-0.187131,False
2,3620,3630,3620~3630,80,79.976111,-0.241778,False
3,3630,3640,3630~3640,80,77.488333,-0.196098,False
4,3640,3650,3640~3650,80,76.990000,-0.339980,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,88.769167,-0.026870,False
956,13160,13170,13160~13170,80,85.985926,0.043605,False
957,13170,13180,13170~13180,80,55.841111,0.005197,False
958,13180,13190,13180~13190,80,84.135556,-0.006575,False
959,13190,13200,13190~13200,80,87.744444,-0.026619,False

============ idx=31, start=93 ============
Vc :  53.7
[2026-07-28 11:58:13] 입력값 | 교통량=2819, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부57-1, 검지기=87, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_094.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_095.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_096.parquet
시드 평균 계산 중...
dc :  4.333333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,87,84.691667,-0.099320,False
1,3610,3620,3610~3620,87,78.327500,-0.197765,False
2,3620,3630,3620~3630,87,76.824026,-0.312268,False
3,3630,3640,3630~3640,87,70.791667,-0.355787,False
4,3640,3650,3640~3650,87,57.800000,-0.293903,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,87,84.964167,-0.001991,False
956,13160,13170,13160~13170,87,85.082630,0.007722,False
957,13170,13180,13170~13180,87,83.080238,0.005294,False
958,13180,13190,13180~13190,87,85.478571,-0.030811,False
959,13190,13200,13190~13200,87,84.136667,0.003869,False

============ idx=32, start=96 ============
Vc :  53.7
[2026-07-28 11:59:30] 입력값 | 교통량=1887, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부48-1,본선부48-2, 검지기=78, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_097.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_098.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_099.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,78,82.616667,-0.215079,False
1,3610,3620,3610~3620,78,81.483333,-0.623675,False
2,3620,3630,3620~3630,78,78.820238,-0.487943,False
3,3630,3640,3630~3640,78,80.129524,-0.635582,False
4,3640,3650,3640~3650,78,73.732381,-0.760654,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,78,56.980556,-0.002635,False
956,13160,13170,13160~13170,78,86.637037,0.005649,False
957,13170,13180,13170~13180,78,84.199167,0.001234,False
958,13180,13190,13180~13190,78,86.527778,-0.014408,False
959,13190,13200,13190~13200,78,84.050000,0.007593,False

============ idx=33, start=99 ============
Vc :  53.7
[2026-07-28 12:00:34] 입력값 | 교통량=2656, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부46-1, 검지기=76, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_100.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_101.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_102.parquet
시드 평균 계산 중...
dc :  3.8333333333333335

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,76,80.990000,-0.186502,False
1,3610,3620,3610~3620,76,80.938333,-0.348982,False
2,3620,3630,3620~3630,76,78.117460,-0.482741,False
3,3630,3640,3630~3640,76,67.421323,-0.552423,False
4,3640,3650,3640~3650,76,61.824167,-0.679884,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,76,58.188889,-0.002600,False
956,13160,13170,13160~13170,76,84.044444,0.035485,False
957,13170,13180,13170~13180,76,81.546667,-0.020278,False
958,13180,13190,13180~13190,76,83.131818,-0.328553,False
959,13190,13200,13190~13200,76,82.031443,-0.010536,False

============ idx=34, start=102 ============
Vc :  53.7
[2026-07-28 12:01:51] 입력값 | 교통량=2542, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부74-1, 검지기=104, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_103.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_104.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_105.parquet
시드 평균 계산 중...
dc :  5.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,104,84.370299,-0.087404,False
1,3610,3620,3610~3620,104,78.732540,-0.172409,False
2,3620,3630,3620~3630,104,78.761111,-0.280428,False
3,3630,3640,3630~3640,104,78.201970,-0.315264,False
4,3640,3650,3640~3650,104,73.849206,-0.490388,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,104,85.365278,0.012717,False
956,13160,13170,13160~13170,104,85.783333,-0.010166,False
957,13170,13180,13170~13180,104,82.620741,0.050645,False
958,13180,13190,13180~13190,104,83.655556,-0.015735,False
959,13190,13200,13190~13200,104,85.141944,0.000732,False

============ idx=35, start=105 ============
Vc :  53.7
[2026-07-28 12:03:06] 입력값 | 교통량=2436, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부52-1,본선부52-2, 검지기=82, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_106.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_107.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_108.parquet
시드 평균 계산 중...
dc :  3.6666666666666665

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,82,80.230556,-0.347746,False
1,3610,3620,3610~3620,82,77.437593,-0.578910,False
2,3620,3630,3620~3630,82,68.150159,-0.782885,False
3,3630,3640,3630~3640,82,55.967857,-1.000000,False
4,3640,3650,3640~3650,82,46.461111,-1.000000,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,82,86.588333,-0.017011,False
956,13160,13170,13160~13170,82,88.175833,-0.006647,False
957,13170,13180,13170~13180,82,85.351389,0.013202,False
958,13180,13190,13180~13190,82,86.405556,-0.020073,False
959,13190,13200,13190~13200,82,86.347778,-0.003590,False

============ idx=36, start=108 ============
Vc :  53.7
[2026-07-28 12:04:16] 입력값 | 교통량=2100, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부81-1, 검지기=111, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_109.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_110.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_111.parquet
시드 평균 계산 중...
dc :  5.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,111,86.060119,-0.147229,False
1,3610,3620,3610~3620,111,81.695556,-0.245854,False
2,3620,3630,3620~3630,111,80.296429,-0.158544,False
3,3630,3640,3630~3640,111,79.823611,-0.293407,False
4,3640,3650,3640~3650,111,79.082143,-0.386032,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,111,84.262963,0.012287,False
956,13160,13170,13160~13170,111,84.302738,-0.009323,False
957,13170,13180,13170~13180,111,89.040000,-0.028680,False
958,13180,13190,13180~13190,111,89.192381,0.016726,False
959,13190,13200,13190~13200,111,86.850000,0.005267,False

============ idx=37, start=111 ============
Vc :  53.7
[2026-07-28 12:05:32] 입력값 | 교통량=2812, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부50-1,본선부50-2, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_112.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_113.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_114.parquet
시드 평균 계산 중...
dc :  3.6666666666666665

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,81.885684,-0.351605,False
1,3610,3620,3610~3620,80,50.095833,-0.376088,True
2,3620,3630,3620~3630,80,69.193056,-0.747337,False
3,3630,3640,3630~3640,80,56.703030,-0.816944,False
4,3640,3650,3640~3650,80,37.505303,-0.960379,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,87.485556,0.010830,False
956,13160,13170,13160~13170,80,83.384444,0.020576,False
957,13170,13180,13170~13180,80,84.017460,-0.007650,False
958,13180,13190,13180~13190,80,85.265934,-0.009476,False
959,13190,13200,13190~13200,80,86.928312,-0.000027,False

============ idx=38, start=114 ============
Vc :  53.7
[2026-07-28 12:06:44] 입력값 | 교통량=2701, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부66-1, 검지기=96, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_115.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_116.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_117.parquet
시드 평균 계산 중...
dc :  4.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,96,85.395000,-0.071147,False
1,3610,3620,3610~3620,96,82.626984,-0.159211,False
2,3620,3630,3620~3630,96,76.888442,-0.140092,False
3,3630,3640,3630~3640,96,66.367607,-0.323774,False
4,3640,3650,3640~3650,96,68.013095,-0.302901,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,96,87.696984,0.019406,False
956,13160,13170,13160~13170,96,85.336667,-0.001882,False
957,13170,13180,13170~13180,96,83.937037,0.009094,False
958,13180,13190,13180~13190,96,84.711111,0.018713,False
959,13190,13200,13190~13200,96,85.534286,0.001649,False

============ idx=39, start=117 ============
Vc :  53.7
[2026-07-28 12:08:03] 입력값 | 교통량=2839, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부79-1,본선부79-2, 검지기=109, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_118.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_119.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_120.parquet
시드 평균 계산 중...
dc :  3.6666666666666665

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,109,81.771429,-0.527478,False
1,3610,3620,3610~3620,109,78.544974,-0.493454,False
2,3620,3630,3620~3630,109,68.105952,-0.733993,False
3,3630,3640,3630~3640,109,56.516931,-0.996899,False
4,3640,3650,3640~3650,109,40.806667,-1.000000,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,109,79.727778,0.041071,False
956,13160,13170,13160~13170,109,77.862179,0.010897,False
957,13170,13180,13170~13180,109,76.855088,0.005753,False
958,13180,13190,13180~13190,109,78.982275,-0.039733,False
959,13190,13200,13190~13200,109,80.019293,-0.047798,False

============ idx=40, start=120 ============
Vc :  53.7
[2026-07-28 12:09:12] 입력값 | 교통량=2971, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부79-1, 검지기=109, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_121.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_122.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_123.parquet
시드 평균 계산 중...
dc :  4.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,109,84.513889,-0.081704,False
1,3610,3620,3610~3620,109,81.516667,-0.189978,False
2,3620,3630,3620~3630,109,72.161538,-0.457218,False
3,3630,3640,3630~3640,109,67.107037,-0.380542,False
4,3640,3650,3640~3650,109,61.721667,-0.526393,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,109,81.803280,-0.015089,False
956,13160,13170,13160~13170,109,86.138624,-0.032513,False
957,13170,13180,13170~13180,109,85.908874,0.021426,False
958,13180,13190,13180~13190,109,84.232273,0.039483,False
959,13190,13200,13190~13200,109,84.250000,-0.009280,False

============ idx=41, start=123 ============
Vc :  53.7
[2026-07-28 12:10:32] 입력값 | 교통량=2504, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부79-1, 검지기=109, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_124.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_125.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_126.parquet
시드 평균 계산 중...
dc :  4.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,109,82.681111,-0.349011,False
1,3610,3620,3610~3620,109,80.933333,-0.055023,False
2,3620,3630,3620~3630,109,72.970513,-0.146961,False
3,3630,3640,3630~3640,109,65.827222,-0.160755,False
4,3640,3650,3640~3650,109,62.367857,-0.670319,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,109,84.415873,-0.014610,False
956,13160,13170,13160~13170,109,89.115000,-0.011748,False
957,13170,13180,13170~13180,109,87.958333,-0.005178,False
958,13180,13190,13180~13190,109,86.048016,0.005830,False
959,13190,13200,13190~13200,109,85.024603,-0.012358,False

============ idx=42, start=126 ============
Vc :  53.7
[2026-07-28 12:11:50] 입력값 | 교통량=2871, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부62-1,본선부62-2, 검지기=92, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_127.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_128.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_129.parquet
시드 평균 계산 중...
dc :  3.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,92,77.152237,-0.260733,False
1,3610,3620,3610~3620,92,70.633455,-0.512819,False
2,3620,3630,3620~3630,92,53.919697,-0.851482,False
3,3630,3640,3630~3640,92,35.743434,-1.000000,True
4,3640,3650,3640~3650,92,21.800000,-0.666667,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,92,68.367484,0.170871,False
956,13160,13170,13160~13170,92,72.752513,0.070929,False
957,13170,13180,13170~13180,92,74.325655,0.099536,False
958,13180,13190,13180~13190,92,78.374722,0.047592,False
959,13190,13200,13190~13200,92,81.932222,0.011223,False

============ idx=43, start=129 ============
링크 번호가 다름
Vc :  53.7
[2026-07-28 12:13:03] 입력값 | 교통량=2486, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부42-1, 검지기=72, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_130.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_131.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_132.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,72,84.691894,-0.095838,False
1,3610,3620,3610~3620,72,83.514352,-0.142803,False
2,3620,3630,3620~3630,72,83.425794,-0.120684,False
3,3630,3640,3630~3640,72,80.584722,-0.195943,False
4,3640,3650,3640~3650,72,77.070513,-0.288181,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,72,88.850000,-0.051239,False
956,13160,13170,13160~13170,72,84.520606,0.038109,False
957,13170,13180,13170~13180,72,85.323333,-0.001457,False
958,13180,13190,13180~13190,72,86.166667,-0.004342,False
959,13190,13200,13190~13200,72,87.992593,-0.043987,False

============ idx=44, start=132 ============
Vc :  53.7
[2026-07-28 12:14:20] 입력값 | 교통량=1967, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부44-1, 검지기=74, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_133.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_134.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_135.parquet
시드 평균 계산 중...
dc :  5.833333333333333

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,74,83.341111,-0.149031,False
1,3610,3620,3610~3620,74,79.798889,-0.206135,False
2,3620,3630,3620~3630,74,77.624242,-0.215938,False
3,3630,3640,3630~3640,74,76.283333,-0.382260,False
4,3640,3650,3640~3650,74,74.990476,-0.494884,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,74,85.682857,-0.005720,False
956,13160,13170,13160~13170,74,85.677778,0.008102,False
957,13170,13180,13170~13180,74,85.648148,-0.001563,False
958,13180,13190,13180~13190,74,85.305556,0.001421,False
959,13190,13200,13190~13200,74,85.216667,0.000884,False

============ idx=45, start=135 ============
Vc :  53.7
[2026-07-28 12:15:38] 입력값 | 교통량=1974, 기존 차로수=2, 유고 차로수=2, 유고지속시간=50, 유고지점=본선부50-1,본선부50-2, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_136.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_137.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_138.parquet
시드 평균 계산 중...
dc :  3.8333333333333335

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,80.113889,-0.294981,False
1,3610,3620,3610~3620,80,79.802500,-0.529918,False
2,3620,3630,3620~3630,80,73.703571,-0.648641,False
3,3630,3640,3630~3640,80,66.167619,-0.890067,False
4,3640,3650,3640~3650,80,54.211111,-1.000000,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,83.970238,0.020110,False
956,13160,13170,13160~13170,80,85.396296,0.003081,False
957,13170,13180,13170~13180,80,85.765833,-0.007448,False
958,13180,13190,13180~13190,80,85.695425,-0.001210,False
959,13190,13200,13190~13200,80,87.273148,-0.003340,False

============ idx=46, start=138 ============
Vc :  53.7
[2026-07-28 12:16:47] 입력값 | 교통량=2668, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부68-1, 검지기=98, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_139.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_140.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_141.parquet
시드 평균 계산 중...
dc :  4.666666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,98,84.019444,-0.154502,False
1,3610,3620,3610~3620,98,81.571944,-0.224961,False
2,3620,3630,3620~3630,98,79.601852,-0.296058,False
3,3630,3640,3630~3640,98,73.693240,-0.326897,False
4,3640,3650,3640~3650,98,73.052222,-0.511218,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,98,84.940000,-0.007437,False
956,13160,13170,13160~13170,98,85.398056,-0.011888,False
957,13170,13180,13170~13180,98,86.105833,-0.005754,False
958,13180,13190,13180~13190,98,89.883333,-0.015510,False
959,13190,13200,13190~13200,98,57.576190,0.021904,False

============ idx=47, start=141 ============
Vc :  53.7
[2026-07-28 12:18:05] 입력값 | 교통량=2069, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부63-1,본선부63-2, 검지기=93, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_142.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_143.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_144.parquet
시드 평균 계산 중...
dc :  3.6666666666666665

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,93,79.400000,-0.280245,False
1,3610,3620,3610~3620,93,77.171356,-0.544772,False
2,3620,3630,3620~3630,93,71.071111,-0.701575,False
3,3630,3640,3630~3640,93,67.673333,-0.920734,False
4,3640,3650,3640~3650,93,46.794444,-0.991430,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,93,83.559722,-0.000678,False
956,13160,13170,13160~13170,93,85.432963,-0.012381,False
957,13170,13180,13170~13180,93,86.231481,-0.011912,False
958,13180,13190,13180~13190,93,86.230000,-0.012419,False
959,13190,13200,13190~13200,93,85.024603,0.013037,False

============ idx=48, start=144 ============
Vc :  53.7
[2026-07-28 12:19:14] 입력값 | 교통량=2969, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부50-1,본선부50-2, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_145.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_146.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_147.parquet
시드 평균 계산 중...
dc :  3.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,83.112963,-0.335547,False
1,3610,3620,3610~3620,80,76.988462,-0.547220,False
2,3620,3630,3620~3630,80,62.579015,-0.708150,False
3,3630,3640,3630~3640,80,39.655833,-0.893854,True
4,3640,3650,3640~3650,80,21.046970,-1.000000,True
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,83.222643,-0.008980,False
956,13160,13170,13160~13170,80,88.134921,0.008607,False
957,13170,13180,13170~13180,80,86.295556,-0.005026,False
958,13180,13190,13180~13190,80,82.088241,0.049514,False
959,13190,13200,13190~13200,80,83.831111,-0.015191,False

============ idx=49, start=147 ============
Vc :  53.7
[2026-07-28 12:20:23] 입력값 | 교통량=2209, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부63-1, 검지기=93, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_148.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_149.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_150.parquet
시드 평균 계산 중...
dc :  5.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,93,78.394444,-0.165967,False
1,3610,3620,3610~3620,93,74.880556,-0.376522,False
2,3620,3630,3620~3630,93,75.713889,-0.391463,False
3,3630,3640,3630~3640,93,73.537500,-0.531515,False
4,3640,3650,3640~3650,93,70.172222,-0.647625,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,93,84.776984,-0.003772,False
956,13160,13170,13160~13170,93,85.110985,-0.006189,False
957,13170,13180,13170~13180,93,85.319444,-0.000980,False
958,13180,13190,13180~13190,93,85.665476,-0.007207,False
959,13190,13200,13190~13200,93,84.182051,-0.003026,False

============ idx=50, start=150 ============
Vc :  53.7
[2026-07-28 12:21:40] 입력값 | 교통량=2857, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부60-1, 검지기=90, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_151.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_152.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_153.parquet
시드 평균 계산 중...
dc :  3.8333333333333335

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,90,81.737108,-0.092943,False
1,3610,3620,3610~3620,90,74.523651,-0.072897,False
2,3620,3630,3620~3630,90,67.776190,-0.069441,False
3,3630,3640,3630~3640,90,62.604127,-0.432621,False
4,3640,3650,3640~3650,90,54.610516,-0.078462,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,90,84.276960,-0.015606,False
956,13160,13170,13160~13170,90,85.921296,-0.000417,False
957,13170,13180,13170~13180,90,86.326455,-0.005488,False
958,13180,13190,13180~13190,90,86.029762,0.004201,False
959,13190,13200,13190~13200,90,85.340427,-0.006347,False

============ idx=51, start=153 ============
Vc :  53.7
[2026-07-28 12:22:59] 입력값 | 교통량=2591, 기존 차로수=2, 유고 차로수=1, 유고지속시간=10, 유고지점=본선부49-1, 검지기=79, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_154.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_155.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_156.parquet
시드 평균 계산 중...
dc :  4.5

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,79,83.512222,-0.148742,False
1,3610,3620,3610~3620,79,79.383333,-0.176421,False
2,3620,3630,3620~3630,79,79.979444,-0.297330,False
3,3630,3640,3630~3640,79,78.968095,-0.254547,False
4,3640,3650,3640~3650,79,76.496667,-0.512168,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,79,85.962222,0.002056,False
956,13160,13170,13160~13170,79,85.212963,0.004430,False
957,13170,13180,13170~13180,79,85.701349,0.001205,False
958,13180,13190,13180~13190,79,85.629167,0.008131,False
959,13190,13200,13190~13200,79,85.661270,-0.006801,False

============ idx=52, start=156 ============
Vc :  53.7
[2026-07-28 12:24:18] 입력값 | 교통량=2100, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부55-1, 검지기=85, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_157.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_158.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_159.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,85,81.083175,-0.203868,False
1,3610,3620,3610~3620,85,81.478333,-0.217678,False
2,3620,3630,3620~3630,85,77.766667,-0.379091,False
3,3630,3640,3630~3640,85,76.651515,-0.379660,False
4,3640,3650,3640~3650,85,74.931429,-0.516739,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,85,86.157143,0.006899,False
956,13160,13170,13160~13170,85,87.778519,-0.006960,False
957,13170,13180,13170~13180,85,85.587407,0.012300,False
958,13180,13190,13180~13190,85,87.702937,-0.011106,False
959,13190,13200,13190~13200,85,85.046667,0.021277,False

============ idx=53, start=159 ============
Vc :  53.7
[2026-07-28 12:25:38] 입력값 | 교통량=1811, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부50-1,본선부50-2, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_160.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_161.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_162.parquet
시드 평균 계산 중...
dc :  3.8333333333333335

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,82.518254,-0.555096,False
1,3610,3620,3610~3620,80,79.816667,-0.457382,False
2,3620,3630,3620~3630,80,79.841905,-0.630193,False
3,3630,3640,3630~3640,80,66.044444,-0.905065,False
4,3640,3650,3640~3650,80,65.266667,-1.000000,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,88.360000,-0.349105,False
956,13160,13170,13160~13170,80,87.450000,-0.003072,False
957,13170,13180,13170~13180,80,90.291667,-0.046120,False
958,13180,13190,13180~13190,80,88.337500,0.055691,False
959,13190,13200,13190~13200,80,83.261111,0.013961,False

============ idx=54, start=162 ============
Vc :  53.7
[2026-07-28 12:26:46] 입력값 | 교통량=2391, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부50-1, 검지기=80, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_163.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_164.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_165.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,80,81.450505,-0.095308,False
1,3610,3620,3610~3620,80,78.420423,-0.249964,False
2,3620,3630,3620~3630,80,74.646667,-0.478239,False
3,3630,3640,3630~3640,80,74.068783,-0.601223,False
4,3640,3650,3640~3650,80,69.397222,-0.678782,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,80,85.408214,0.022515,False
956,13160,13170,13160~13170,80,85.037374,0.013694,False
957,13170,13180,13170~13180,80,85.758333,-0.016755,False
958,13180,13190,13180~13190,80,86.203889,-0.005009,False
959,13190,13200,13190~13200,80,85.161111,0.014361,False

============ idx=55, start=165 ============
Vc :  53.7
[2026-07-28 12:28:02] 입력값 | 교통량=2824, 기존 차로수=2, 유고 차로수=1, 유고지속시간=30, 유고지점=본선부62-1, 검지기=92, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_166.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_167.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_168.parquet
시드 평균 계산 중...
dc :  4.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,92,83.713333,-0.496439,False
1,3610,3620,3610~3620,92,79.911190,-0.189482,False
2,3620,3630,3620~3630,92,75.347222,-0.396360,False
3,3630,3640,3630~3640,92,67.264762,-0.340570,False
4,3640,3650,3640~3650,92,66.392222,-0.327875,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,92,83.658333,0.005241,False
956,13160,13170,13160~13170,92,84.372222,0.001732,False
957,13170,13180,13170~13180,92,85.669048,-0.025208,False
958,13180,13190,13180~13190,92,83.019345,0.005660,False
959,13190,13200,13190~13200,92,82.962004,0.014558,False

============ idx=56, start=168 ============
Vc :  53.7
[2026-07-28 12:29:20] 입력값 | 교통량=1804, 기존 차로수=2, 유고 차로수=2, 유고지속시간=60, 유고지점=본선부44-1,본선부44-2, 검지기=74, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_169.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_170.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_171.parquet
시드 평균 계산 중...
dc :  4.0

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,74,82.468333,-0.262675,False
1,3610,3620,3610~3620,74,80.813889,-0.521743,False
2,3620,3630,3620~3630,74,50.161111,-0.494367,True
3,3630,3640,3630~3640,74,50.350000,-0.568371,True
4,3640,3650,3640~3650,74,60.541111,-0.885653,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,74,86.972698,-0.020340,False
956,13160,13170,13160~13170,74,58.213333,0.008150,False
957,13170,13180,13170~13180,74,90.983333,-0.033631,False
958,13180,13190,13180~13190,74,89.502222,0.028172,False
959,13190,13200,13190~13200,74,59.665000,-0.008506,False

============ idx=57, start=171 ============
Vc :  53.7
[2026-07-28 12:30:25] 입력값 | 교통량=2878, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부49-1, 검지기=79, lane_gradient=-0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_172.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_173.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_174.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,79,80.069597,-0.130831,False
1,3610,3620,3610~3620,79,76.399495,-0.266552,False
2,3620,3630,3620~3630,79,73.922222,-0.420297,False
3,3630,3640,3630~3640,79,64.312500,-0.555931,False
4,3640,3650,3640~3650,79,67.900487,-0.727552,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,79,85.496667,0.011372,False
956,13160,13170,13160~13170,79,85.022381,-0.020795,False
957,13170,13180,13170~13180,79,56.053333,0.005335,False
958,13180,13190,13180~13190,79,81.498779,-0.005401,False
959,13190,13200,13190~13200,79,81.446368,-0.002132,False

============ idx=58, start=174 ============
Vc :  53.7
[2026-07-28 12:31:43] 입력값 | 교통량=2593, 기존 차로수=2, 유고 차로수=1, 유고지속시간=20, 유고지점=본선부74-1, 검지기=104, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_175.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_176.parquet
작업파일 : 화성~서울(140-본선부_구간2)_260426_177.parquet
시드 평균 계산 중...
dc :  4.166666666666667

'speed_after : '

,StartTime,EndTime,TimeGroup,New_Measurement,V_mean,delta_V,is_congested
0,3600,3610,3600~3610,104,82.127778,-0.067516,False
1,3610,3620,3610~3620,104,79.318095,-0.185044,False
2,3620,3630,3620~3630,104,78.899365,-0.293862,False
3,3630,3640,3630~3640,104,79.076591,-0.392701,False
4,3640,3650,3640~3650,104,74.000000,-0.597150,False
...,...,...,...,...,...,...,...
955,13150,13160,13150~13160,104,87.395648,-0.011585,False
956,13160,13170,13160~13170,104,84.749735,0.014679,False
957,13170,13180,13170~13180,104,85.588889,-0.006926,False
958,13180,13190,13180~13190,104,86.732222,-0.003397,False
959,13190,13200,13190~13200,104,84.134615,0.010858,False

============ idx=59, start=177 ============
Vc :  53.7
[2026-07-28 12:32:59] 입력값 | 교통량=2159, 기존 차로수=2, 유고 차로수=1, 유고지속시간=5, 유고지점=본선부62-1, 검지기=92, lane_gradient=0.005
작업파일 : 화성~서울(140-본선부_구간2)_260426_178.parquet

KeyboardInterrupt: